close all;
clear all;
N=1000;
n=13000;
K=32;

p=4;
px=1;
py=1;
pz=4;
N_bar = N / px;
n_bar = n / pz;

Tflop=8.33*10-11;
Treduce=2*10-6;
Tallgather=2*10-6;
Tsendrecv=2*10-6;

T1 = ( N.^2 + ... 
       n.*(10.*N.^2+2) + ... 
       2*N.^2 + N.^2 + ... 
       N .* (3.*K.*N-K) + ... 
       n.*N.*(5*K+3) + ... 
       N.*(1+2.*n) ...
     ) .* Tflop;
 
Tcomp = ( n_bar .* (2+3.*N_bar.^2) + ...
          N_bar .^2 + ...
          N_bar .^2 .* n_bar * 7 + ...
          2 * N_bar .^2 + ...
          N_bar .^2 + ...
          N_bar .* (3*K.*N_bar+3*N_bar-3*K.^2-K) + ...
          2*px*K.*N_bar + ...
          N_bar .* (2*K+(px*K-K).*(3*K+3)) + ...
          n_bar .* N_bar .*(1+7*K) + ...
          2*n_bar .* N_bar + ...
          N_bar .* (2+n_bar) + ...
          N_bar .* n_bar ...
        ).*Tflop;
        
Tcomm = ( n_bar * Treduce + ...
          (N_bar .^2) .* Treduce + ...
          (N_bar .^2) .* Tsendrecv + ...
          N_bar .* K .* Tallgather + ...
          (n_bar .* N_bar) .* Treduce + ...
          N_bar .* Treduce ...
        );
Tcomm = 0.0351*Tcomp;
%Tcomp = (6*N.^2*n./q+N.^2./q+N.^2.*log2(N./p)./q+p.*K+n.*N.*K./p+n2.*N./p+2*n.*N./p).*Tflop
%Tcomm = (n.*p.*log2(p)+2*p.*K)*Ttransmit
%T1=(6*N.^2*n+N.^2+N.^2.*log2(N)+K*n.*N+n2.*N+2*n.*N)*Tflop
speedup = T1 ./ (Tcomm+Tcomp)
figure;
plot(N,speedup,'--rs','LineWidth',3,...
    'MarkerFaceColor','g',...
    'MarkerEdgeColor','k',...
    'MarkerSize',10);
xlabel('Number of Samples: 2000 \leq N \leq 60000');
ylabel('Speedup');
title('Speedup curves');
disp('... Done');


%R810
Time_real = [4778.5 5273.2 6559.5 9007.4 12327.5 17151.96 20340.9 26374.1 33812.9 51324.3 105417.4];
Time_real = fliplr(Time_real);

np   = [1 2 3 4 5 6 8 12 16 20 24 ];

Time_ideal = 105417.4 ./ np;

figure;
plot(np, Time_ideal,'g','LineWidth',2,...
    'MarkerFaceColor','b',...
    'MarkerEdgeColor','k',...
    'MarkerSize',6);
hold on;
plot(np, Time_real,'--rs','LineWidth',3,...
    'MarkerFaceColor','g',...
    'MarkerEdgeColor','k',...
    'MarkerSize',10);
xlabel('Number of Processors');
ylabel('Time in Seconds');
title('Speedup curves: observed v.s. ideal');
disp('... Done');

















